name: Go on Windows

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"

      -name: Install pcap
        run: |
          Invoke-WebRequest -Uri https://nmap.org/npcap/dist/npcap-1.60.exe -OutFile npcap-1.60.exe
          Start-Process -FilePath npcap-1.60.exe -ArgumentList '/S' -Wait    

      - name: Build amd64
        run: |
          set GOARCH=amd64
          go build -v ./...
        shell: cmd

      - name: Build arm64
        run: |
          set GOARCH=arm64
          go build -v ./...
        shell: cmd

